import type { Collection } from "./types.ts";

export const collections: Collection[] = [
  {
    id: "collection-birds",
    slug: "birds",
    number: "01",
    title: "Birds",
    subtitle: "The aerial life of a continent, held in stillness.",
    description:
      "A study of flight, feather, and color — from the painted bunting's impossible palette to the small dramas of the air.",
    photoIds: [
      "photo-painted-bunting-salvia",
      "photo-painted-bunting-portrait",
      "photo-painted-bunting-flight",
      "photo-california-quail",
      "photo-roadrunner-dinner",
      "photo-hummingbird-nest",
      "photo-painted-bunting-green-leaves",
      "photo-wood-duck-flight",
      "photo-bald-eagle-pair",
      "photo-wood-duck-portrait",
      "photo-red-shouldered-hawk-feeding",
      "photo-roadrunner-snake",
      "photo-barred-owl-portrait",
      "photo-indigo-bunting-wings-raised",
      "photo-crow-portrait",
      "photo-scissor-tailed-flycatcher-insect-toss",
      "photo-roadrunner-portrait",
      "photo-painted-buntings-interaction",
      "photo-painted-bunting-sunflowers-flight",
      "photo-painted-bunting-sunflower-bee",
      "photo-downy-woodpecker",
    ],
    coverPhotoId: "photo-painted-bunting-salvia",
    coverLocation: "Location — to be confirmed",
    featured: true,
  },
  {
    id: "collection-mammals",
    slug: "mammals",
    number: "02",
    title: "Mammals",
    subtitle: "The intelligence of a gaze. The weight of an animal at rest.",
    description:
      "Portraits made close, but never intrusively — a quiet catalogue of the animals that share these forests, deserts, and coastlines.",
    photoIds: [
      "photo-bobcat-hero",
      "photo-red-foxes",
      "photo-otter-carrying-fish",
      "photo-otter-family-swimming",
      "photo-raccoon-tree-hollow",
      "photo-otter-open-mouth",
      "photo-otter-carrying-object",
      "photo-coyote-standing",
      "photo-coyote-portrait",
      "photo-beaver-lodge",
      "photo-bobcat-walking",
      "photo-bobcat-profile",
      "photo-deer-fawn",
    ],
    coverPhotoId: "photo-red-foxes",
    coverLocation: "Northern Woodlands",
    featured: true,
  },
  {
    id: "collection-behavior",
    slug: "behavior",
    number: "03",
    title: "Wildlife Behavior",
    subtitle: "The moments most photographers miss.",
    description:
      "The hunt, the courtship, the feeding of a chick — behavior seen only after long hours of stillness, and rarely captured whole.",
    photoIds: [
      "photo-roadrunner-dinner",
      "photo-green-anole-dewlap",
      "photo-red-shouldered-hawk-feeding",
      "photo-roadrunner-snake",
      "photo-scissor-tailed-flycatcher-insect-toss",
      "photo-longhorn-beetle-flight",
      "photo-painted-buntings-interaction",
      "photo-painted-bunting-sunflower-bee",
      "photo-sphinx-moth-hovering",
      "photo-dragonfly-head-on-flight",
    ],
    coverPhotoId: "photo-roadrunner-dinner",
    coverLocation: "Desert Southwest",
    featured: true,
  },
  {
    id: "collection-conservation",
    slug: "conservation",
    number: "04",
    title: "Conservation",
    subtitle: "Small lives whose futures hang on the choices being made today.",
    description:
      "A hummingbird nest, no larger than a walnut — photographed in the hope that seeing these lives clearly is the first step toward keeping them here.",
    photoIds: ["photo-hummingbird-nest"],
    coverPhotoId: "photo-hummingbird-nest",
    coverLocation: "Backyard Oak",
    featured: true,
  },
];
