import type { Photo, ResponsiveImage } from "./types.ts";

const webpSrcSet = (stem: string, widths: number[]) =>
  widths.map((width) => `/images/${stem}-${width}.webp ${width}w`).join(", ");

export const responsiveImages: Record<string, ResponsiveImage> = {
  bobcat: {
    key: "bobcat",
    src: "/images/bobcat-hero.jpg",
    width: 3840,
    height: 2561,
    webpSrcSet: webpSrcSet("bobcat-hero", [960, 1600, 2400, 3840]),
  },
  "painted-bunting-salvia": {
    key: "painted-bunting-salvia",
    src: "/images/birds-painted-bunting-salvia.jpg",
    width: 2841,
    height: 1894,
    webpSrcSet: webpSrcSet("birds-painted-bunting-salvia", [960, 1600, 2400, 2841]),
  },
  "painted-bunting-flight": {
    key: "painted-bunting-flight",
    src: "/images/birds-bunting-in-flight.jpg",
    width: 3200,
    height: 3200,
    webpSrcSet: webpSrcSet("birds-bunting-in-flight", [960, 1600, 2400, 3200]),
  },
  "california-quail": {
    key: "california-quail",
    src: "/images/birds-california-quail.jpg",
    width: 3093,
    height: 3092,
    webpSrcSet: webpSrcSet("birds-california-quail", [960, 1600, 2400, 3093]),
  },
  foxes: {
    key: "foxes",
    src: "/images/mammals-fox.jpg",
    width: 2184,
    height: 1456,
    webpSrcSet: webpSrcSet("mammals-fox", [960, 1600, 2184]),
  },
  roadrunners: {
    key: "roadrunners",
    src: "/images/behavior-roadrunner.jpg",
    width: 3200,
    height: 2134,
    webpSrcSet: webpSrcSet("behavior-roadrunner", [960, 1600, 2400, 3200]),
  },
  "hummingbird-nest": {
    key: "hummingbird-nest",
    src: "/images/conservation-hummingbird-nest.jpg",
    width: 3200,
    height: 2129,
    webpSrcSet: webpSrcSet("conservation-hummingbird-nest", [960, 1600, 2400, 3200]),
  },
  "otter-carrying-fish": {
    key: "otter-carrying-fish",
    src: "/images/otter-carrying-fish.jpg",
    width: 3200,
    height: 2133,
    webpSrcSet: webpSrcSet("otter-carrying-fish", [960, 1600, 2400, 3200]),
  },
  "painted-bunting-green-leaves": {
    key: "painted-bunting-green-leaves",
    src: "/images/painted-bunting-green-leaves.jpg",
    width: 3840,
    height: 2559,
    webpSrcSet: webpSrcSet("painted-bunting-green-leaves", [960, 1600, 2400, 3840]),
  },
  "wood-duck-flight": {
    key: "wood-duck-flight",
    src: "/images/wood-duck-flight.jpg",
    width: 3458,
    height: 3458,
    webpSrcSet: webpSrcSet("wood-duck-flight", [960, 1600, 2400, 3458]),
  },
  "bald-eagle-pair": {
    key: "bald-eagle-pair",
    src: "/images/bald-eagle-pair.jpg",
    width: 3468,
    height: 3468,
    webpSrcSet: webpSrcSet("bald-eagle-pair", [960, 1600, 2400, 3468]),
  },
  "otter-family-swimming": {
    key: "otter-family-swimming",
    src: "/images/otter-family-swimming.jpg",
    width: 2129,
    height: 1419,
    webpSrcSet: webpSrcSet("otter-family-swimming", [960, 1600, 2129]),
  },
  "green-anole-dewlap": {
    key: "green-anole-dewlap",
    src: "/images/green-anole-dewlap.jpg",
    width: 1481,
    height: 1481,
    webpSrcSet: webpSrcSet("green-anole-dewlap", [960, 1481]),
  },
  "wood-duck-portrait": {
    key: "wood-duck-portrait",
    src: "/images/wood-duck-portrait.jpg",
    width: 3200,
    height: 3200,
    webpSrcSet: webpSrcSet("wood-duck-portrait", [960, 1600, 2400, 3200]),
  },
  "red-shouldered-hawk-feeding": {
    key: "red-shouldered-hawk-feeding",
    src: "/images/red-shouldered-hawk-feeding.jpg",
    width: 3200,
    height: 3200,
    webpSrcSet: webpSrcSet("red-shouldered-hawk-feeding", [960, 1600, 2400, 3200]),
  },
  tarantula: {
    key: "tarantula",
    src: "/images/tarantula.jpg",
    width: 3200,
    height: 2133,
    webpSrcSet: webpSrcSet("tarantula", [960, 1600, 2400, 3200]),
  },
  "paul-portrait": {
    key: "paul-portrait",
    src: "/images/about-paul-portrait.png",
    width: 742,
    height: 638,
    webpSrcSet: "/images/about-paul-portrait-742.webp 742w",
  },
};

// Compatibility keys used by the separate operational catalog and legacy
// placeholder slots. New public routes should pass `responsiveImageKey`.
export const imageAliases: Record<string, string> = {
  "hero.jpg": "bobcat",
  "birds-painted-bunting.jpg": "painted-bunting-salvia",
  "birds-painted-bunting-salvia.jpg": "painted-bunting-salvia",
  "birds-painted-bunting-flight.jpg": "painted-bunting-flight",
  "birds-california-quail.jpg": "california-quail",
  "mammals-fox.jpg": "foxes",
  "behavior-roadrunner-feeding-chick.jpg": "roadrunners",
  "story-roadrunner.jpg": "roadrunners",
  "story-dinner-is-served.jpg": "roadrunners",
  "story-07.jpg": "roadrunners",
  "conservation-hummingbird-nest.jpg": "hummingbird-nest",
  "about-portrait.jpg": "paul-portrait",
};

const base = {
  behaviors: [],
  habitats: [],
  storyIds: [],
  heroCandidate: false,
  educationSuitable: false,
  conservationTopics: [],
  photographerCredit: "Paul Marto",
  featured: false,
  galleryVisible: true,
} satisfies Partial<Photo>;

export const photos: Photo[] = [
  {
    ...base,
    id: "photo-bobcat-hero",
    slug: "bobcat-portrait",
    title: "Title Pending Artist Approval",
    status: "awaiting-title",
    image: "/images/bobcat-hero.jpg",
    responsiveImageKey: "bobcat",
    alt: "Bobcat watching from the edge of tall grass",
    speciesId: "species-bobcat",
    orientation: "landscape",
    category: "mammals",
    collectionIds: ["collection-mammals"],
    printId: "print-bobcat",
    featured: true,
    heroCandidate: true,
    focus: "right",
    galleryVisible: false,
    shortCaption: "Bobcat through the grass",
  },
  {
    ...base,
    id: "photo-painted-bunting-salvia",
    slug: "painted-bunting-on-salvia",
    title: "Title Pending Artist Approval",
    status: "awaiting-title",
    image: "/images/birds-painted-bunting-salvia.jpg",
    responsiveImageKey: "painted-bunting-salvia",
    alt: "Painted Bunting on salvia",
    speciesId: "species-painted-bunting",
    orientation: "landscape",
    location: "Location — to be confirmed",
    year: 2024,
    shortCaption: "A male painted bunting perched on a spray of purple salvia.",
    category: "birds",
    collectionIds: ["collection-birds"],
    printId: "print-painted-bunting-salvia",
    featured: true,
    ratio: "aspect-[3/2]",
    focus: "left",
  },
  {
    ...base,
    id: "photo-painted-bunting-portrait",
    slug: "painted-bunting-portrait",
    title: "Title Pending Artist Approval",
    status: "awaiting-title",
    missingImageFilename: "birds-painted-bunting-portrait.jpg",
    alt: "Formal side portrait of a male Painted Bunting",
    speciesId: "species-painted-bunting",
    orientation: "landscape",
    location: "Location — to be confirmed",
    year: 2024,
    shortCaption:
      "A formal side portrait of a male painted bunting against a clean, neutral background.",
    category: "birds",
    collectionIds: ["collection-birds"],
    printId: "print-painted-bunting-portrait",
    ratio: "aspect-[3/2]",
    focus: "center",
  },
  {
    ...base,
    id: "photo-painted-bunting-flight",
    slug: "painted-bunting-in-flight",
    title: "Impossible Blue",
    status: "published",
    image: "/images/birds-bunting-in-flight.jpg",
    responsiveImageKey: "painted-bunting-flight",
    alt: "Painted Bunting in flight with wings open",
    speciesId: "species-painted-bunting",
    orientation: "square",
    location: "Location — to be confirmed",
    year: 2024,
    shortCaption:
      "Wings open, head down, eye locked. A single frame from a bird that rarely holds still long enough to be seen at all.",
    storyBody: [
      "A bunting in mid-flight is measured in fractions of a second. The wings blur; the eye does not. You wait, and wait, and then the shutter chooses for you.",
      "This frame arrived on the eleventh morning of a quiet week — patience rewarded not with a landing, but with an animal briefly suspended between one branch and the next.",
      "It remains one of the truest portraits I have made of what wildlife photography actually is: hours of stillness, and then a single breath of light.",
    ],
    category: "birds",
    collectionIds: ["collection-birds"],
    printId: "print-painted-bunting-flight",
    ratio: "aspect-square",
  },
  {
    ...base,
    id: "photo-california-quail",
    slug: "california-quail-portrait",
    title: "The Plume",
    status: "published",
    image: "/images/birds-california-quail.jpg",
    responsiveImageKey: "california-quail",
    alt: "California Quail portrait showing its plume",
    speciesId: "species-california-quail",
    orientation: "square",
    location: "Location — to be confirmed",
    year: 2024,
    shortCaption:
      "A male quail turns his head a quarter inch and the whole portrait arrives — the crest, the scaled breast, the wet-black eye.",
    storyBody: [
      "The California Quail is our state bird, and one of the most quietly ornamented animals in the West. Everything about him is drawn — the comma of the crest, the white brushstrokes on the face, the fine scaling on the belly.",
      "This frame came at the end of a long, still afternoon. He stepped up onto a low branch, held the pose for a heartbeat, and looked past the lens as if he had somewhere to be.",
      "It is a portrait, more than a wildlife photograph — but the light and the wildness are entirely his.",
    ],
    category: "birds",
    collectionIds: ["collection-birds"],
    printId: "print-california-quail",
    ratio: "aspect-[4/5]",
  },
  {
    ...base,
    id: "photo-red-foxes",
    slug: "red-fox-golden-hour",
    title: "Ember",
    status: "published",
    image: "/images/mammals-fox.jpg",
    responsiveImageKey: "foxes",
    alt: "Two red foxes meeting at golden hour",
    speciesId: "species-red-fox",
    orientation: "landscape",
    location: "Location — to be confirmed",
    year: 2024,
    shortCaption:
      "Two young foxes cross paths in the last minute of sun. They held the light for four breaths, then were gone.",
    category: "mammals",
    collectionIds: ["collection-mammals"],
    printId: "print-foxes",
    featured: true,
    ratio: "aspect-[4/5]",
  },
  {
    ...base,
    id: "photo-roadrunner-dinner",
    slug: "roadrunner-dinner",
    title: "Dinner Is Served",
    status: "published",
    image: "/images/behavior-roadrunner.jpg",
    responsiveImageKey: "roadrunners",
    alt: "Roadrunner parent feeding its chick",
    speciesId: "species-greater-roadrunner",
    orientation: "landscape",
    location: "Location — to be confirmed",
    year: 2024,
    shortCaption:
      "A parent returns to a hidden nest with a lizard the length of its own body. The chick called for it for twenty minutes.",
    storyBody: [
      "The nest was tucked into the arms of a cholla the size of a small car. I had marked it two weeks earlier without ever getting closer than eighty yards.",
      "The chick had a voice like a rusty gate. When the parent came back — every ninety minutes or so — it would call as if the world were ending.",
      "This frame is the exchange itself. A lizard as long as the chick was, hanging in the air between two open beaks, held for perhaps a fifth of a second.",
      "The chick swallowed it whole. It looked, for a moment, like a small dinosaur that had made a terrible mistake.",
    ],
    behaviors: ["parental feeding"],
    category: "behavior",
    collectionIds: ["collection-behavior"],
    storyIds: ["story-dinner-is-served"],
    printId: "print-dinner-is-served",
    featured: true,
    educationSuitable: true,
    ratio: "aspect-[16/10]",
    focus: "right",
    span: true,
  },
  {
    ...base,
    id: "photo-hummingbird-nest",
    slug: "hummingbird-nest",
    title: "The Nest",
    status: "published",
    image: "/images/conservation-hummingbird-nest.jpg",
    responsiveImageKey: "hummingbird-nest",
    alt: "Hummingbird returning to its nest",
    speciesId: "species-annas-hummingbird",
    orientation: "landscape",
    location: "Location — to be confirmed",
    year: 2024,
    shortCaption:
      "A mother returns to a nest the size of a walnut. Two chicks, no larger than jellybeans, wait for her every ten minutes.",
    behaviors: ["nesting"],
    category: "conservation",
    collectionIds: ["collection-conservation"],
    printId: "print-hummingbird-nest",
    featured: true,
    educationSuitable: true,
    conservationTopics: ["nesting habitat"],
    ratio: "aspect-[4/5]",
    focus: "left",
  },
  {
    ...base,
    id: "photo-paul-portrait",
    slug: "paul-marto-portrait",
    title: "Paul Marto",
    status: "published",
    image: "/images/about-paul-portrait.png",
    responsiveImageKey: "paul-portrait",
    alt: "Paul Marto, wildlife photographer",
    orientation: "landscape",
    category: "mammals",
    collectionIds: [],
    galleryVisible: false,
  },
  {
    ...base,
    id: "photo-otter-carrying-fish",
    slug: "otter-carrying-fish",
    title: "Title Pending Artist Approval",
    workingTitle: "Otter carrying fish",
    status: "published",
    image: "/images/otter-carrying-fish.jpg",
    responsiveImageKey: "otter-carrying-fish",
    alt: "North American River Otter holding a fish in its mouth at the water's edge",
    speciesId: "species-north-american-river-otter",
    orientation: "landscape",
    category: "mammals",
    collectionIds: [],
  },
  {
    ...base,
    id: "photo-painted-bunting-green-leaves",
    slug: "painted-bunting-green-leaves",
    title: "Title Pending Artist Approval",
    workingTitle: "Painted Bunting perched among green leaves",
    status: "published",
    image: "/images/painted-bunting-green-leaves.jpg",
    responsiveImageKey: "painted-bunting-green-leaves",
    alt: "Male Painted Bunting perched among green leaves",
    speciesId: "species-painted-bunting",
    orientation: "landscape",
    category: "birds",
    collectionIds: [],
  },
  {
    ...base,
    id: "photo-wood-duck-flight",
    slug: "wood-duck-flight",
    title: "Title Pending Artist Approval",
    workingTitle: "Wood Duck in flight",
    status: "published",
    image: "/images/wood-duck-flight.jpg",
    responsiveImageKey: "wood-duck-flight",
    alt: "Male Wood Duck flying with wings extended",
    speciesId: "species-wood-duck",
    orientation: "square",
    category: "birds",
    collectionIds: [],
  },
  {
    ...base,
    id: "photo-bald-eagle-pair",
    slug: "bald-eagle-pair",
    title: "Title Pending Artist Approval",
    workingTitle: "Bald Eagle pair",
    status: "published",
    image: "/images/bald-eagle-pair.jpg",
    responsiveImageKey: "bald-eagle-pair",
    alt: "Two Bald Eagles perched together on a branch against a blue sky",
    speciesId: "species-bald-eagle",
    orientation: "square",
    category: "birds",
    collectionIds: [],
  },
  {
    ...base,
    id: "photo-otter-family-swimming",
    slug: "otter-family-swimming",
    title: "Title Pending Artist Approval",
    workingTitle: "Otter family swimming",
    status: "published",
    image: "/images/otter-family-swimming.jpg",
    responsiveImageKey: "otter-family-swimming",
    alt: "Three North American River Otters swimming together",
    speciesId: "species-north-american-river-otter",
    orientation: "landscape",
    category: "mammals",
    collectionIds: [],
  },
  {
    ...base,
    id: "photo-green-anole-dewlap",
    slug: "green-anole-dewlap",
    title: "Title Pending Artist Approval",
    workingTitle: "Green anole displaying dewlap",
    status: "published",
    image: "/images/green-anole-dewlap.jpg",
    responsiveImageKey: "green-anole-dewlap",
    alt: "Green Anole displaying a pink dewlap",
    speciesId: "species-green-anole",
    orientation: "square",
    category: "behavior",
    collectionIds: [],
  },
  {
    ...base,
    id: "photo-wood-duck-portrait",
    slug: "wood-duck-portrait",
    title: "Title Pending Artist Approval",
    workingTitle: "Wood Duck frontal portrait",
    status: "published",
    image: "/images/wood-duck-portrait.jpg",
    responsiveImageKey: "wood-duck-portrait",
    alt: "Frontal portrait of a male Wood Duck",
    speciesId: "species-wood-duck",
    orientation: "square",
    category: "birds",
    collectionIds: [],
  },
  {
    ...base,
    id: "photo-red-shouldered-hawk-feeding",
    slug: "red-shouldered-hawk-feeding",
    title: "Title Pending Artist Approval",
    workingTitle: "Red-shouldered Hawk feeding",
    status: "published",
    image: "/images/red-shouldered-hawk-feeding.jpg",
    responsiveImageKey: "red-shouldered-hawk-feeding",
    alt: "Red-shouldered Hawk bending to feed on prey",
    speciesId: "species-red-shouldered-hawk",
    orientation: "square",
    category: "behavior",
    collectionIds: [],
  },
  {
    ...base,
    id: "photo-tarantula",
    slug: "tarantula",
    title: "Title Pending Artist Approval",
    workingTitle: "Tarantula",
    status: "published",
    image: "/images/tarantula.jpg",
    responsiveImageKey: "tarantula",
    alt: "Brown tarantula walking across small stones",
    speciesId: "species-tarantula",
    orientation: "landscape",
    category: "conservation",
    collectionIds: [],
  },
];
