import type { Photo, ResponsiveImage } from "./types.ts";

const webpSrcSet = (stem: string, widths: number[]) =>
  widths.map((width) => `/images/${stem}-${width}.webp ${width}w`).join(", ");

export const responsiveImages: Record<string, ResponsiveImage> = {
  bobcat: {
    key: "bobcat",
    src: "/images/bobcat-hero.jpg",
    width: 3840,
    height: 2561,
    webpSrcSet: webpSrcSet("bobcat-hero", [960, 1600, 2400, 3840]),
  },
  "painted-bunting-salvia": {
    key: "painted-bunting-salvia",
    src: "/images/birds-painted-bunting-salvia.jpg",
    width: 2841,
    height: 1894,
    webpSrcSet: webpSrcSet("birds-painted-bunting-salvia", [960, 1600, 2400, 2841]),
  },
  "painted-bunting-flight": {
    key: "painted-bunting-flight",
    src: "/images/birds-bunting-in-flight.jpg",
    width: 3200,
    height: 3200,
    webpSrcSet: webpSrcSet("birds-bunting-in-flight", [960, 1600, 2400, 3200]),
  },
  "california-quail": {
    key: "california-quail",
    src: "/images/birds-california-quail.jpg",
    width: 3093,
    height: 3092,
    webpSrcSet: webpSrcSet("birds-california-quail", [960, 1600, 2400, 3093]),
  },
  foxes: {
    key: "foxes",
    src: "/images/mammals-fox.jpg",
    width: 2184,
    height: 1456,
    webpSrcSet: webpSrcSet("mammals-fox", [960, 1600, 2184]),
  },
  roadrunners: {
    key: "roadrunners",
    src: "/images/behavior-roadrunner.jpg",
    width: 3200,
    height: 2134,
    webpSrcSet: webpSrcSet("behavior-roadrunner", [960, 1600, 2400, 3200]),
  },
  "hummingbird-nest": {
    key: "hummingbird-nest",
    src: "/images/conservation-hummingbird-nest.jpg",
    width: 3200,
    height: 2129,
    webpSrcSet: webpSrcSet("conservation-hummingbird-nest", [960, 1600, 2400, 3200]),
  },
  "otter-carrying-fish": {
    key: "otter-carrying-fish",
    src: "/images/otter-carrying-fish.jpg",
    width: 3200,
    height: 2133,
    webpSrcSet: webpSrcSet("otter-carrying-fish", [960, 1600, 2400, 3200]),
  },
  "painted-bunting-green-leaves": {
    key: "painted-bunting-green-leaves",
    src: "/images/painted-bunting-green-leaves.jpg",
    width: 3840,
    height: 2559,
    webpSrcSet: webpSrcSet("painted-bunting-green-leaves", [960, 1600, 2400, 3840]),
  },
  "wood-duck-flight": {
    key: "wood-duck-flight",
    src: "/images/wood-duck-flight.jpg",
    width: 3458,
    height: 3458,
    webpSrcSet: webpSrcSet("wood-duck-flight", [960, 1600, 2400, 3458]),
  },
  "bald-eagle-pair": {
    key: "bald-eagle-pair",
    src: "/images/bald-eagle-pair.jpg",
    width: 3468,
    height: 3468,
    webpSrcSet: webpSrcSet("bald-eagle-pair", [960, 1600, 2400, 3468]),
  },
  "otter-family-swimming": {
    key: "otter-family-swimming",
    src: "/images/otter-family-swimming.jpg",
    width: 2129,
    height: 1419,
    webpSrcSet: webpSrcSet("otter-family-swimming", [960, 1600, 2129]),
  },
  "green-anole-dewlap": {
    key: "green-anole-dewlap",
    src: "/images/green-anole-dewlap.jpg",
    width: 1481,
    height: 1481,
    webpSrcSet: webpSrcSet("green-anole-dewlap", [960, 1481]),
  },
  "wood-duck-portrait": {
    key: "wood-duck-portrait",
    src: "/images/wood-duck-portrait.jpg",
    width: 3200,
    height: 3200,
    webpSrcSet: webpSrcSet("wood-duck-portrait", [960, 1600, 2400, 3200]),
  },
  "red-shouldered-hawk-feeding": {
    key: "red-shouldered-hawk-feeding",
    src: "/images/red-shouldered-hawk-feeding.jpg",
    width: 3200,
    height: 3200,
    webpSrcSet: webpSrcSet("red-shouldered-hawk-feeding", [960, 1600, 2400, 3200]),
  },
  tarantula: {
    key: "tarantula",
    src: "/images/tarantula.jpg",
    width: 3200,
    height: 2133,
    webpSrcSet: webpSrcSet("tarantula", [960, 1600, 2400, 3200]),
  },
  "copperhead-tongue": {
    key: "copperhead-tongue",
    src: "/images/copperhead-tongue.jpg",
    width: 3840,
    height: 2560,
    webpSrcSet: webpSrcSet("copperhead-tongue", [960, 1600, 2400, 3840]),
  },
  "horse-fly-reflection": {
    key: "horse-fly-reflection",
    src: "/images/horse-fly-reflection.jpg",
    width: 3200,
    height: 3200,
    webpSrcSet: webpSrcSet("horse-fly-reflection", [960, 1600, 2400, 3200]),
  },
  "raccoon-tree-hollow": {
    key: "raccoon-tree-hollow",
    src: "/images/raccoon-tree-hollow.jpg",
    width: 3200,
    height: 3200,
    webpSrcSet: webpSrcSet("raccoon-tree-hollow", [960, 1600, 2400, 3200]),
  },
  "roadrunner-snake": {
    key: "roadrunner-snake",
    src: "/images/roadrunner-snake.jpg",
    width: 3200,
    height: 3200,
    webpSrcSet: webpSrcSet("roadrunner-snake", [960, 1600, 2400, 3200]),
  },
  "barred-owl-portrait": {
    key: "barred-owl-portrait",
    src: "/images/barred-owl-portrait.jpg",
    width: 2559,
    height: 3840,
    webpSrcSet: webpSrcSet("barred-owl-portrait", [960, 1600, 2400, 2559]),
  },
  "indigo-bunting-wings-raised": {
    key: "indigo-bunting-wings-raised",
    src: "/images/indigo-bunting-wings-raised.jpg",
    width: 3200,
    height: 3200,
    webpSrcSet: webpSrcSet("indigo-bunting-wings-raised", [960, 1600, 2400, 3200]),
  },
  "crow-portrait": {
    key: "crow-portrait",
    src: "/images/crow-portrait.jpg",
    width: 3200,
    height: 3200,
    webpSrcSet: webpSrcSet("crow-portrait", [960, 1600, 2400, 3200]),
  },
  "scissor-tailed-flycatcher-insect-toss": {
    key: "scissor-tailed-flycatcher-insect-toss",
    src: "/images/scissor-tailed-flycatcher-insect-toss.jpg",
    width: 3840,
    height: 2560,
    webpSrcSet: webpSrcSet("scissor-tailed-flycatcher-insect-toss", [960, 1600, 2400, 3840]),
  },
  "longhorn-beetle-flight": {
    key: "longhorn-beetle-flight",
    src: "/images/longhorn-beetle-flight.jpg",
    width: 3200,
    height: 3200,
    webpSrcSet: webpSrcSet("longhorn-beetle-flight", [960, 1600, 2400, 3200]),
  },
  "blue-wasp-white-flowers": {
    key: "blue-wasp-white-flowers",
    src: "/images/blue-wasp-white-flowers.jpg",
    width: 3200,
    height: 3200,
    webpSrcSet: webpSrcSet("blue-wasp-white-flowers", [960, 1600, 2400, 3200]),
  },
  "roadrunner-portrait": {
    key: "roadrunner-portrait",
    src: "/images/roadrunner-portrait.jpg",
    width: 2431,
    height: 2431,
    webpSrcSet: webpSrcSet("roadrunner-portrait", [960, 1600, 2431]),
  },
  "painted-buntings-interaction": {
    key: "painted-buntings-interaction",
    src: "/images/painted-buntings-interaction.jpg",
    width: 1316,
    height: 1316,
    webpSrcSet: webpSrcSet("painted-buntings-interaction", [960, 1316]),
  },
  "painted-bunting-sunflowers-flight": {
    key: "painted-bunting-sunflowers-flight",
    src: "/images/painted-bunting-sunflowers-flight.jpg",
    width: 3840,
    height: 2559,
    webpSrcSet: webpSrcSet("painted-bunting-sunflowers-flight", [960, 1600, 2400, 3840]),
  },
  "painted-bunting-sunflower-bee": {
    key: "painted-bunting-sunflower-bee",
    src: "/images/painted-bunting-sunflower-bee.jpg",
    width: 1968,
    height: 1968,
    webpSrcSet: webpSrcSet("painted-bunting-sunflower-bee", [960, 1600, 1968]),
  },
  "downy-woodpecker": {
    key: "downy-woodpecker",
    src: "/images/downy-woodpecker.jpg",
    width: 2029,
    height: 2029,
    webpSrcSet: webpSrcSet("downy-woodpecker", [960, 1600, 2029]),
  },
  "sphinx-moth-hovering": {
    key: "sphinx-moth-hovering",
    src: "/images/sphinx-moth-hovering.jpg",
    width: 2383,
    height: 2383,
    webpSrcSet: webpSrcSet("sphinx-moth-hovering", [960, 1600, 2383]),
  },
  "dragonfly-head-on-flight": {
    key: "dragonfly-head-on-flight",
    src: "/images/dragonfly-head-on-flight.jpg",
    width: 3840,
    height: 2559,
    webpSrcSet: webpSrcSet("dragonfly-head-on-flight", [960, 1600, 2400, 3840]),
  },
  "otter-open-mouth": {
    key: "otter-open-mouth",
    src: "/images/otter-open-mouth.jpg",
    width: 2400,
    height: 1599,
    webpSrcSet: webpSrcSet("otter-open-mouth", [960, 1600, 2400]),
  },
  "otter-carrying-object": {
    key: "otter-carrying-object",
    src: "/images/otter-carrying-object.jpg",
    width: 1456,
    height: 1456,
    webpSrcSet: webpSrcSet("otter-carrying-object", [960, 1456]),
  },
  "paul-portrait": {
    key: "paul-portrait",
    src: "/images/about-paul-portrait.png",
    width: 742,
    height: 638,
    webpSrcSet: "/images/about-paul-portrait-742.webp 742w",
  },
};

// Compatibility keys used by the separate operational catalog and legacy
// placeholder slots. New public routes should pass `responsiveImageKey`.
export const imageAliases: Record<string, string> = {
  "hero.jpg": "bobcat",
  "birds-painted-bunting.jpg": "painted-bunting-salvia",
  "birds-painted-bunting-salvia.jpg": "painted-bunting-salvia",
  "birds-painted-bunting-flight.jpg": "painted-bunting-flight",
  "birds-california-quail.jpg": "california-quail",
  "mammals-fox.jpg": "foxes",
  "behavior-roadrunner-feeding-chick.jpg": "roadrunners",
  "story-roadrunner.jpg": "roadrunners",
  "story-dinner-is-served.jpg": "roadrunners",
  "story-07.jpg": "roadrunners",
  "conservation-hummingbird-nest.jpg": "hummingbird-nest",
  "about-portrait.jpg": "paul-portrait",
};

const base = {
  behaviors: [],
  habitats: [],
  storyIds: [],
  heroCandidate: false,
  educationSuitable: false,
  conservationTopics: [],
  photographerCredit: "Paul Marto",
  featured: false,
  galleryVisible: true,
} satisfies Partial<Photo>;

export const photos: Photo[] = [
  {
    ...base,
    id: "photo-bobcat-hero",
    slug: "bobcat-portrait",
    title: "Title Pending Artist Approval",
    status: "awaiting-title",
    image: "/images/bobcat-hero.jpg",
    responsiveImageKey: "bobcat",
    alt: "Bobcat watching from the edge of tall grass",
    speciesId: "species-bobcat",
    orientation: "landscape",
    category: "mammals",
    collectionIds: ["collection-mammals"],
    printId: "print-bobcat",
    featured: true,
    heroCandidate: true,
    focus: "right",
    galleryVisible: false,
    shortCaption: "Bobcat through the grass",
  },
  {
    ...base,
    id: "photo-painted-bunting-salvia",
    slug: "painted-bunting-on-salvia",
    title: "Title Pending Artist Approval",
    status: "awaiting-title",
    image: "/images/birds-painted-bunting-salvia.jpg",
    responsiveImageKey: "painted-bunting-salvia",
    alt: "Painted Bunting on salvia",
    speciesId: "species-painted-bunting",
    orientation: "landscape",
    location: "Location — to be confirmed",
    year: 2024,
    shortCaption: "A male painted bunting perched on a spray of purple salvia.",
    category: "birds",
    collectionIds: ["collection-birds"],
    printId: "print-painted-bunting-salvia",
    featured: true,
    ratio: "aspect-[3/2]",
    focus: "left",
  },
  {
    ...base,
    id: "photo-painted-bunting-portrait",
    slug: "painted-bunting-portrait",
    title: "Title Pending Artist Approval",
    status: "awaiting-title",
    missingImageFilename: "birds-painted-bunting-portrait.jpg",
    alt: "Formal side portrait of a male Painted Bunting",
    speciesId: "species-painted-bunting",
    orientation: "landscape",
    location: "Location — to be confirmed",
    year: 2024,
    shortCaption:
      "A formal side portrait of a male painted bunting against a clean, neutral background.",
    category: "birds",
    collectionIds: ["collection-birds"],
    printId: "print-painted-bunting-portrait",
    ratio: "aspect-[3/2]",
    focus: "center",
    galleryVisible: false,
  },
  {
    ...base,
    id: "photo-painted-bunting-flight",
    slug: "painted-bunting-in-flight",
    title: "Impossible Blue",
    status: "published",
    image: "/images/birds-bunting-in-flight.jpg",
    responsiveImageKey: "painted-bunting-flight",
    alt: "Painted Bunting in flight with wings open",
    speciesId: "species-painted-bunting",
    orientation: "square",
    location: "Location — to be confirmed",
    year: 2024,
    shortCaption:
      "Wings open, head down, eye locked. A single frame from a bird that rarely holds still long enough to be seen at all.",
    storyBody: [
      "A bunting in mid-flight is measured in fractions of a second. The wings blur; the eye does not. You wait, and wait, and then the shutter chooses for you.",
      "This frame arrived on the eleventh morning of a quiet week — patience rewarded not with a landing, but with an animal briefly suspended between one branch and the next.",
      "It remains one of the truest portraits I have made of what wildlife photography actually is: hours of stillness, and then a single breath of light.",
    ],
    category: "birds",
    collectionIds: ["collection-birds"],
    printId: "print-painted-bunting-flight",
    ratio: "aspect-square",
  },
  {
    ...base,
    id: "photo-california-quail",
    slug: "california-quail-portrait",
    title: "The Plume",
    status: "published",
    image: "/images/birds-california-quail.jpg",
    responsiveImageKey: "california-quail",
    alt: "California Quail portrait showing its plume",
    speciesId: "species-california-quail",
    orientation: "square",
    location: "Location — to be confirmed",
    year: 2024,
    shortCaption:
      "A male quail turns his head a quarter inch and the whole portrait arrives — the crest, the scaled breast, the wet-black eye.",
    storyBody: [
      "The California Quail is our state bird, and one of the most quietly ornamented animals in the West. Everything about him is drawn — the comma of the crest, the white brushstrokes on the face, the fine scaling on the belly.",
      "This frame came at the end of a long, still afternoon. He stepped up onto a low branch, held the pose for a heartbeat, and looked past the lens as if he had somewhere to be.",
      "It is a portrait, more than a wildlife photograph — but the light and the wildness are entirely his.",
    ],
    category: "birds",
    collectionIds: ["collection-birds"],
    printId: "print-california-quail",
    ratio: "aspect-[4/5]",
  },
  {
    ...base,
    id: "photo-red-foxes",
    slug: "red-fox-golden-hour",
    title: "Ember",
    status: "published",
    image: "/images/mammals-fox.jpg",
    responsiveImageKey: "foxes",
    alt: "Two red foxes meeting at golden hour",
    speciesId: "species-red-fox",
    orientation: "landscape",
    location: "Location — to be confirmed",
    year: 2024,
    shortCaption:
      "Two young foxes cross paths in the last minute of sun. They held the light for four breaths, then were gone.",
    category: "mammals",
    collectionIds: ["collection-mammals"],
    printId: "print-foxes",
    galleryOrder: 5,
    featured: true,
    ratio: "aspect-[4/5]",
  },
  {
    ...base,
    id: "photo-roadrunner-dinner",
    slug: "roadrunner-dinner",
    title: "Dinner Is Served",
    status: "published",
    image: "/images/behavior-roadrunner.jpg",
    responsiveImageKey: "roadrunners",
    alt: "Roadrunner parent feeding its chick",
    speciesId: "species-greater-roadrunner",
    orientation: "landscape",
    location: "Location — to be confirmed",
    year: 2024,
    shortCaption:
      "A parent returns to a hidden nest with a lizard the length of its own body. The chick called for it for twenty minutes.",
    storyBody: [
      "The nest was tucked into the arms of a cholla the size of a small car. I had marked it two weeks earlier without ever getting closer than eighty yards.",
      "The chick had a voice like a rusty gate. When the parent came back — every ninety minutes or so — it would call as if the world were ending.",
      "This frame is the exchange itself. A lizard as long as the chick was, hanging in the air between two open beaks, held for perhaps a fifth of a second.",
      "The chick swallowed it whole. It looked, for a moment, like a small dinosaur that had made a terrible mistake.",
    ],
    behaviors: ["parental feeding"],
    category: "behavior",
    collectionIds: ["collection-behavior"],
    storyIds: ["story-dinner-is-served"],
    printId: "print-dinner-is-served",
    featured: true,
    educationSuitable: true,
    ratio: "aspect-[16/10]",
    focus: "right",
    span: true,
  },
  {
    ...base,
    id: "photo-hummingbird-nest",
    slug: "hummingbird-nest",
    title: "The Nest",
    status: "published",
    image: "/images/conservation-hummingbird-nest.jpg",
    responsiveImageKey: "hummingbird-nest",
    alt: "Hummingbird returning to its nest",
    speciesId: "species-annas-hummingbird",
    orientation: "landscape",
    location: "Location — to be confirmed",
    year: 2024,
    shortCaption:
      "A mother returns to a nest the size of a walnut. Two chicks, no larger than jellybeans, wait for her every ten minutes.",
    behaviors: ["nesting"],
    category: "conservation",
    collectionIds: ["collection-conservation"],
    printId: "print-hummingbird-nest",
    featured: true,
    educationSuitable: true,
    conservationTopics: ["nesting habitat"],
    ratio: "aspect-[4/5]",
    focus: "left",
  },
  {
    ...base,
    id: "photo-paul-portrait",
    slug: "paul-marto-portrait",
    title: "Paul Marto",
    status: "published",
    image: "/images/about-paul-portrait.png",
    responsiveImageKey: "paul-portrait",
    alt: "Paul Marto, wildlife photographer",
    orientation: "landscape",
    category: "mammals",
    collectionIds: [],
    galleryVisible: false,
  },
  {
    ...base,
    id: "photo-otter-carrying-fish",
    slug: "otter-carrying-fish",
    title: "Title Pending Artist Approval",
    workingTitle: "Otter carrying fish",
    status: "published",
    image: "/images/otter-carrying-fish.jpg",
    responsiveImageKey: "otter-carrying-fish",
    alt: "North American River Otter holding a fish in its mouth at the water's edge",
    speciesId: "species-north-american-river-otter",
    orientation: "landscape",
    category: "mammals",
    collectionIds: [],
    galleryOrder: 2,
  },
  {
    ...base,
    id: "photo-painted-bunting-green-leaves",
    slug: "painted-bunting-green-leaves",
    title: "Title Pending Artist Approval",
    workingTitle: "Painted Bunting perched among green leaves",
    status: "published",
    image: "/images/painted-bunting-green-leaves.jpg",
    responsiveImageKey: "painted-bunting-green-leaves",
    alt: "Male Painted Bunting perched among green leaves",
    speciesId: "species-painted-bunting",
    orientation: "landscape",
    category: "birds",
    collectionIds: [],
  },
  {
    ...base,
    id: "photo-wood-duck-flight",
    slug: "wood-duck-flight",
    title: "Title Pending Artist Approval",
    workingTitle: "Wood Duck in flight",
    status: "published",
    image: "/images/wood-duck-flight.jpg",
    responsiveImageKey: "wood-duck-flight",
    alt: "Male Wood Duck flying with wings extended",
    speciesId: "species-wood-duck",
    orientation: "square",
    category: "birds",
    collectionIds: [],
  },
  {
    ...base,
    id: "photo-bald-eagle-pair",
    slug: "bald-eagle-pair",
    title: "Title Pending Artist Approval",
    workingTitle: "Bald Eagle pair",
    status: "published",
    image: "/images/bald-eagle-pair.jpg",
    responsiveImageKey: "bald-eagle-pair",
    alt: "Two Bald Eagles perched together on a branch against a blue sky",
    speciesId: "species-bald-eagle",
    orientation: "square",
    category: "birds",
    collectionIds: [],
  },
  {
    ...base,
    id: "photo-otter-family-swimming",
    slug: "otter-family-swimming",
    title: "Title Pending Artist Approval",
    workingTitle: "Otter family swimming",
    status: "published",
    image: "/images/otter-family-swimming.jpg",
    responsiveImageKey: "otter-family-swimming",
    alt: "Three North American River Otters swimming together",
    speciesId: "species-north-american-river-otter",
    orientation: "landscape",
    category: "mammals",
    collectionIds: [],
  },
  {
    ...base,
    id: "photo-green-anole-dewlap",
    slug: "green-anole-dewlap",
    title: "Title Pending Artist Approval",
    workingTitle: "Green anole displaying dewlap",
    status: "published",
    image: "/images/green-anole-dewlap.jpg",
    responsiveImageKey: "green-anole-dewlap",
    alt: "Green Anole displaying a pink dewlap",
    speciesId: "species-green-anole",
    orientation: "square",
    category: "behavior",
    collectionIds: [],
  },
  {
    ...base,
    id: "photo-wood-duck-portrait",
    slug: "wood-duck-portrait",
    title: "Title Pending Artist Approval",
    workingTitle: "Wood Duck frontal portrait",
    status: "published",
    image: "/images/wood-duck-portrait.jpg",
    responsiveImageKey: "wood-duck-portrait",
    alt: "Frontal portrait of a male Wood Duck",
    speciesId: "species-wood-duck",
    orientation: "square",
    category: "birds",
    collectionIds: [],
  },
  {
    ...base,
    id: "photo-red-shouldered-hawk-feeding",
    slug: "red-shouldered-hawk-feeding",
    title: "Title Pending Artist Approval",
    workingTitle: "Red-shouldered Hawk feeding",
    status: "published",
    image: "/images/red-shouldered-hawk-feeding.jpg",
    responsiveImageKey: "red-shouldered-hawk-feeding",
    alt: "Red-shouldered Hawk bending to feed on prey",
    speciesId: "species-red-shouldered-hawk",
    orientation: "square",
    category: "behavior",
    collectionIds: [],
  },
  {
    ...base,
    id: "photo-tarantula",
    slug: "tarantula",
    title: "Title Pending Artist Approval",
    workingTitle: "Tarantula",
    status: "published",
    image: "/images/tarantula.jpg",
    responsiveImageKey: "tarantula",
    alt: "Brown tarantula walking across small stones",
    speciesId: "species-tarantula",
    orientation: "landscape",
    category: "conservation",
    collectionIds: [],
  },
  {
    ...base,
    id: "photo-copperhead-tongue",
    slug: "copperhead-tongue",
    title: "Title Pending Artist Approval",
    workingTitle: "Copperhead with tongue extended",
    status: "draft",
    image: "/images/copperhead-tongue.jpg",
    responsiveImageKey: "copperhead-tongue",
    alt: "Copperhead resting with its red forked tongue extended",
    speciesId: "species-copperhead",
    orientation: "landscape",
    behaviors: ["tongue flicking"],
    category: "conservation",
    collectionIds: [],
    educationSuitable: true,
    galleryVisible: false,
  },
  {
    ...base,
    id: "photo-horse-fly-reflection",
    slug: "horse-fly-reflection",
    title: "Title Pending Artist Approval",
    workingTitle: "Horse fly with reflection",
    status: "published",
    image: "/images/horse-fly-reflection.jpg",
    responsiveImageKey: "horse-fly-reflection",
    alt: "Horse fly standing above its reflection on a smooth surface",
    speciesId: "species-horse-fly",
    orientation: "square",
    category: "conservation",
    collectionIds: [],
    educationSuitable: true,
    galleryVisible: true,
    galleryOrder: 3,
  },
  {
    ...base,
    id: "photo-raccoon-tree-hollow",
    slug: "raccoon-tree-hollow",
    title: "Title Pending Artist Approval",
    workingTitle: "Raccoon peering from a tree hollow",
    status: "draft",
    image: "/images/raccoon-tree-hollow.jpg",
    responsiveImageKey: "raccoon-tree-hollow",
    alt: "Raccoon peering over wood from inside a tree hollow",
    speciesId: "species-raccoon",
    orientation: "square",
    category: "mammals",
    collectionIds: [],
    educationSuitable: true,
    galleryVisible: false,
  },
  {
    ...base,
    id: "photo-roadrunner-snake",
    slug: "roadrunner-snake",
    title: "Title Pending Artist Approval",
    workingTitle: "Roadrunner carrying a snake",
    status: "draft",
    image: "/images/roadrunner-snake.jpg",
    responsiveImageKey: "roadrunner-snake",
    alt: "Greater Roadrunner holding a striped snake in its beak",
    speciesId: "species-greater-roadrunner",
    orientation: "square",
    behaviors: ["carrying prey"],
    category: "behavior",
    collectionIds: [],
    educationSuitable: true,
    galleryVisible: false,
  },
  {
    ...base,
    id: "photo-barred-owl-portrait",
    slug: "barred-owl-portrait",
    title: "Title Pending Artist Approval",
    workingTitle: "Barred Owl portrait",
    status: "draft",
    image: "/images/barred-owl-portrait.jpg",
    responsiveImageKey: "barred-owl-portrait",
    alt: "Barred Owl perched among bare branches with its eyes closed",
    speciesId: "species-barred-owl",
    orientation: "portrait",
    category: "birds",
    collectionIds: [],
    educationSuitable: true,
    galleryVisible: false,
  },
  {
    ...base,
    id: "photo-indigo-bunting-wings-raised",
    slug: "indigo-bunting-wings-raised",
    title: "Title Pending Artist Approval",
    workingTitle: "Indigo Bunting with wings raised",
    status: "draft",
    image: "/images/indigo-bunting-wings-raised.jpg",
    responsiveImageKey: "indigo-bunting-wings-raised",
    alt: "Male Indigo Bunting perched with both wings raised",
    speciesId: "species-indigo-bunting",
    orientation: "square",
    category: "birds",
    collectionIds: [],
    galleryVisible: false,
  },
  {
    ...base,
    id: "photo-crow-portrait",
    slug: "crow-portrait",
    title: "Title Pending Artist Approval",
    workingTitle: "Crow portrait",
    status: "draft",
    image: "/images/crow-portrait.jpg",
    responsiveImageKey: "crow-portrait",
    alt: "Black crow perched against a softly blurred yellow and green background",
    orientation: "square",
    category: "birds",
    collectionIds: [],
    educationSuitable: true,
    galleryVisible: false,
  },
  {
    ...base,
    id: "photo-scissor-tailed-flycatcher-insect-toss",
    slug: "scissor-tailed-flycatcher-insect-toss",
    title: "Title Pending Artist Approval",
    workingTitle: "Scissor-tailed Flycatcher tossing an insect",
    status: "published",
    image: "/images/scissor-tailed-flycatcher-insect-toss.jpg",
    responsiveImageKey: "scissor-tailed-flycatcher-insect-toss",
    alt: "Scissor-tailed Flycatcher tossing an insect above its open beak",
    speciesId: "species-scissor-tailed-flycatcher",
    orientation: "landscape",
    behaviors: ["prey handling"],
    category: "behavior",
    collectionIds: [],
    educationSuitable: true,
    galleryVisible: true,
    galleryOrder: 4,
  },
  {
    ...base,
    id: "photo-longhorn-beetle-flight",
    slug: "longhorn-beetle-flight",
    title: "Title Pending Artist Approval",
    workingTitle: "Longhorn beetle in flight",
    status: "published",
    image: "/images/longhorn-beetle-flight.jpg",
    responsiveImageKey: "longhorn-beetle-flight",
    alt: "Black and yellow longhorn beetle flying head-on with antennae extended",
    speciesId: "species-cottonwood-borer",
    orientation: "square",
    behaviors: ["flight"],
    category: "behavior",
    collectionIds: [],
    educationSuitable: true,
    galleryVisible: true,
    galleryOrder: 9,
  },
  {
    ...base,
    id: "photo-blue-wasp-white-flowers",
    slug: "blue-wasp-white-flowers",
    title: "Title Pending Artist Approval",
    workingTitle: "Metallic blue wasp on white flowers",
    status: "draft",
    image: "/images/blue-wasp-white-flowers.jpg",
    responsiveImageKey: "blue-wasp-white-flowers",
    alt: "Metallic blue wasp resting on a cluster of small white flowers",
    orientation: "square",
    category: "conservation",
    collectionIds: [],
    educationSuitable: true,
    galleryVisible: false,
  },
  {
    ...base,
    id: "photo-roadrunner-portrait",
    slug: "roadrunner-portrait",
    title: "Title Pending Artist Approval",
    workingTitle: "Roadrunner portrait",
    status: "draft",
    image: "/images/roadrunner-portrait.jpg",
    responsiveImageKey: "roadrunner-portrait",
    alt: "Close portrait of a Greater Roadrunner with its crest raised",
    speciesId: "species-greater-roadrunner",
    orientation: "square",
    category: "birds",
    collectionIds: [],
    galleryVisible: false,
  },
  {
    ...base,
    id: "photo-painted-buntings-interaction",
    slug: "painted-buntings-interaction",
    title: "Title Pending Artist Approval",
    workingTitle: "Painted Buntings interacting in flight",
    status: "published",
    image: "/images/painted-buntings-interaction.jpg",
    responsiveImageKey: "painted-buntings-interaction",
    alt: "Two male Painted Buntings facing each other with wings spread",
    speciesId: "species-painted-bunting",
    orientation: "square",
    behaviors: ["interaction", "flight"],
    category: "behavior",
    collectionIds: [],
    galleryVisible: true,
    galleryOrder: 7,
  },
  {
    ...base,
    id: "photo-painted-bunting-sunflowers-flight",
    slug: "painted-bunting-sunflowers-flight",
    title: "Title Pending Artist Approval",
    workingTitle: "Painted Bunting in flight among sunflowers",
    status: "published",
    image: "/images/painted-bunting-sunflowers-flight.jpg",
    responsiveImageKey: "painted-bunting-sunflowers-flight",
    alt: "Male Painted Bunting flying above a sunflower with wings raised",
    speciesId: "species-painted-bunting",
    orientation: "landscape",
    behaviors: ["flight"],
    category: "birds",
    collectionIds: [],
    galleryVisible: true,
    galleryOrder: 1,
  },
  {
    ...base,
    id: "photo-painted-bunting-sunflower-bee",
    slug: "painted-bunting-sunflower-bee",
    title: "Title Pending Artist Approval",
    workingTitle: "Painted Bunting, sunflower, and bee",
    status: "published",
    image: "/images/painted-bunting-sunflower-bee.jpg",
    responsiveImageKey: "painted-bunting-sunflower-bee",
    alt: "Male Painted Bunting perched on a sunflower as a bee approaches",
    speciesId: "species-painted-bunting",
    orientation: "square",
    category: "behavior",
    collectionIds: [],
    educationSuitable: true,
    galleryVisible: true,
    galleryOrder: 8,
  },
  {
    ...base,
    id: "photo-downy-woodpecker",
    slug: "downy-woodpecker",
    title: "Title Pending Artist Approval",
    workingTitle: "Downy Woodpecker on tree trunk",
    status: "draft",
    image: "/images/downy-woodpecker.jpg",
    responsiveImageKey: "downy-woodpecker",
    alt: "Downy Woodpecker clinging to the side of a tree trunk",
    speciesId: "species-downy-woodpecker",
    orientation: "square",
    category: "birds",
    collectionIds: [],
    educationSuitable: true,
    galleryVisible: false,
  },
  {
    ...base,
    id: "photo-sphinx-moth-hovering",
    slug: "sphinx-moth-hovering",
    title: "Title Pending Artist Approval",
    workingTitle: "Sphinx moth hovering at a flower",
    status: "draft",
    image: "/images/sphinx-moth-hovering.jpg",
    responsiveImageKey: "sphinx-moth-hovering",
    alt: "White-lined Sphinx Moth hovering beside a pink flower",
    speciesId: "species-white-lined-sphinx-moth",
    orientation: "square",
    behaviors: ["hovering"],
    category: "behavior",
    collectionIds: [],
    educationSuitable: true,
    galleryVisible: false,
  },
  {
    ...base,
    id: "photo-dragonfly-head-on-flight",
    slug: "dragonfly-head-on-flight",
    title: "Title Pending Artist Approval",
    workingTitle: "Dragonfly in head-on flight",
    status: "published",
    image: "/images/dragonfly-head-on-flight.jpg",
    responsiveImageKey: "dragonfly-head-on-flight",
    alt: "Green and blue dragonfly flying head-on with four wings extended",
    speciesId: "species-common-green-darner",
    orientation: "landscape",
    behaviors: ["flight"],
    category: "behavior",
    collectionIds: [],
    educationSuitable: true,
    galleryVisible: true,
    galleryOrder: 6,
  },
  {
    ...base,
    id: "photo-otter-open-mouth",
    slug: "otter-open-mouth",
    title: "Title Pending Artist Approval",
    workingTitle: "Otter with mouth open",
    status: "draft",
    image: "/images/otter-open-mouth.jpg",
    responsiveImageKey: "otter-open-mouth",
    alt: "North American River Otter standing among logs with its mouth open",
    speciesId: "species-north-american-river-otter",
    orientation: "landscape",
    category: "mammals",
    collectionIds: [],
    galleryVisible: false,
  },
  {
    ...base,
    id: "photo-otter-carrying-object",
    slug: "otter-carrying-object",
    title: "Title Pending Artist Approval",
    workingTitle: "Otter carrying a green object",
    status: "draft",
    image: "/images/otter-carrying-object.jpg",
    responsiveImageKey: "otter-carrying-object",
    alt: "North American River Otter swimming with a round green object in its mouth",
    speciesId: "species-north-american-river-otter",
    orientation: "square",
    behaviors: ["carrying an object"],
    category: "mammals",
    collectionIds: [],
    galleryVisible: false,
  },
];
