import type { Species } from "./types.ts";

export const species: Species[] = [
  {
    id: "species-bobcat",
    slug: "bobcat",
    commonName: "Bobcat",
    scientificName: "Lynx rufus",
    category: "mammals",
    photoIds: ["photo-bobcat-hero"],
  },
  {
    id: "species-painted-bunting",
    slug: "painted-bunting",
    commonName: "Painted Bunting",
    scientificName: "Passerina ciris",
    category: "birds",
    photoIds: [
      "photo-painted-bunting-salvia",
      "photo-painted-bunting-portrait",
      "photo-painted-bunting-flight",
      "photo-painted-bunting-green-leaves",
    ],
  },
  {
    id: "species-california-quail",
    slug: "california-quail",
    commonName: "California Quail",
    scientificName: "Callipepla californica",
    category: "birds",
    photoIds: ["photo-california-quail"],
  },
  {
    id: "species-red-fox",
    slug: "red-fox",
    commonName: "Red Fox",
    scientificName: "Vulpes vulpes",
    category: "mammals",
    photoIds: ["photo-red-foxes"],
  },
  {
    id: "species-greater-roadrunner",
    slug: "greater-roadrunner",
    commonName: "Greater Roadrunner",
    scientificName: "Geococcyx californianus",
    category: "behavior",
    photoIds: ["photo-roadrunner-dinner"],
  },
  {
    id: "species-annas-hummingbird",
    slug: "annas-hummingbird",
    commonName: "Anna's Hummingbird",
    scientificName: "Calypte anna",
    category: "conservation",
    photoIds: ["photo-hummingbird-nest"],
  },
  {
    id: "species-north-american-river-otter",
    slug: "north-american-river-otter",
    commonName: "North American River Otter",
    category: "mammals",
    photoIds: ["photo-otter-carrying-fish", "photo-otter-family-swimming"],
  },
  {
    id: "species-red-shouldered-hawk",
    slug: "red-shouldered-hawk",
    commonName: "Red-shouldered Hawk",
    category: "birds",
    photoIds: ["photo-red-shouldered-hawk-feeding"],
  },
  {
    id: "species-green-anole",
    slug: "green-anole",
    commonName: "Green Anole",
    category: "behavior",
    photoIds: ["photo-green-anole-dewlap"],
  },
  {
    id: "species-tarantula",
    slug: "tarantula",
    commonName: "Tarantula",
    category: "conservation",
    photoIds: ["photo-tarantula"],
  },
  {
    id: "species-wood-duck",
    slug: "wood-duck",
    commonName: "Wood Duck",
    category: "birds",
    photoIds: ["photo-wood-duck-portrait", "photo-wood-duck-flight"],
  },
  {
    id: "species-bald-eagle",
    slug: "bald-eagle",
    commonName: "Bald Eagle",
    category: "birds",
    photoIds: ["photo-bald-eagle-pair"],
  },
];
