import type { Species } from "./types.ts";

export const species: Species[] = [
  {
    id: "species-bobcat",
    slug: "bobcat",
    commonName: "Bobcat",
    scientificName: "Lynx rufus",
    category: "mammals",
    photoIds: ["photo-bobcat-hero", "photo-bobcat-walking", "photo-bobcat-profile"],
  },
  {
    id: "species-painted-bunting",
    slug: "painted-bunting",
    commonName: "Painted Bunting",
    scientificName: "Passerina ciris",
    category: "birds",
    photoIds: [
      "photo-painted-bunting-salvia",
      "photo-painted-bunting-portrait",
      "photo-painted-bunting-flight",
      "photo-painted-bunting-green-leaves",
      "photo-painted-buntings-interaction",
      "photo-painted-bunting-sunflowers-flight",
      "photo-painted-bunting-sunflower-bee",
    ],
  },
  {
    id: "species-california-quail",
    slug: "california-quail",
    commonName: "California Quail",
    scientificName: "Callipepla californica",
    category: "birds",
    photoIds: ["photo-california-quail"],
  },
  {
    id: "species-red-fox",
    slug: "red-fox",
    commonName: "Red Fox",
    scientificName: "Vulpes vulpes",
    category: "mammals",
    photoIds: ["photo-red-foxes"],
  },
  {
    id: "species-greater-roadrunner",
    slug: "greater-roadrunner",
    commonName: "Greater Roadrunner",
    scientificName: "Geococcyx californianus",
    category: "birds",
    photoIds: ["photo-roadrunner-dinner", "photo-roadrunner-snake", "photo-roadrunner-portrait"],
  },
  {
    id: "species-annas-hummingbird",
    slug: "annas-hummingbird",
    commonName: "Anna's Hummingbird",
    scientificName: "Calypte anna",
    category: "birds",
    photoIds: ["photo-hummingbird-nest"],
  },
  {
    id: "species-north-american-river-otter",
    slug: "north-american-river-otter",
    commonName: "North American River Otter",
    category: "mammals",
    photoIds: [
      "photo-otter-carrying-fish",
      "photo-otter-family-swimming",
      "photo-otter-open-mouth",
      "photo-otter-carrying-object",
    ],
  },
  {
    id: "species-red-shouldered-hawk",
    slug: "red-shouldered-hawk",
    commonName: "Red-shouldered Hawk",
    category: "birds",
    photoIds: ["photo-red-shouldered-hawk-feeding"],
  },
  {
    id: "species-green-anole",
    slug: "green-anole",
    commonName: "Green Anole",
    category: "reptiles",
    photoIds: ["photo-green-anole-dewlap"],
  },
  {
    id: "species-tarantula",
    slug: "tarantula",
    commonName: "Tarantula",
    category: "arachnids",
    photoIds: ["photo-tarantula"],
  },
  {
    id: "species-wood-duck",
    slug: "wood-duck",
    commonName: "Wood Duck",
    category: "birds",
    photoIds: ["photo-wood-duck-portrait", "photo-wood-duck-flight"],
  },
  {
    id: "species-bald-eagle",
    slug: "bald-eagle",
    commonName: "Bald Eagle",
    category: "birds",
    photoIds: ["photo-bald-eagle-pair"],
  },
  {
    id: "species-copperhead",
    slug: "copperhead",
    commonName: "Copperhead",
    category: "reptiles",
    photoIds: ["photo-copperhead-tongue"],
  },
  {
    id: "species-horse-fly",
    slug: "horse-fly",
    commonName: "Horse Fly",
    category: "insects",
    photoIds: ["photo-horse-fly-reflection"],
  },
  {
    id: "species-raccoon",
    slug: "raccoon",
    commonName: "Raccoon",
    category: "mammals",
    photoIds: ["photo-raccoon-tree-hollow"],
  },
  {
    id: "species-barred-owl",
    slug: "barred-owl",
    commonName: "Barred Owl",
    category: "birds",
    photoIds: ["photo-barred-owl-portrait"],
  },
  {
    id: "species-indigo-bunting",
    slug: "indigo-bunting",
    commonName: "Indigo Bunting",
    category: "birds",
    photoIds: ["photo-indigo-bunting-wings-raised"],
  },
  {
    id: "species-scissor-tailed-flycatcher",
    slug: "scissor-tailed-flycatcher",
    commonName: "Scissor-tailed Flycatcher",
    scientificName: "Tyrannus forficatus",
    category: "birds",
    photoIds: ["photo-scissor-tailed-flycatcher-insect-toss"],
  },
  {
    id: "species-cottonwood-borer",
    slug: "cottonwood-borer",
    commonName: "Cottonwood Borer",
    scientificName: "Plectrodera scalator",
    category: "insects",
    photoIds: ["photo-longhorn-beetle-flight"],
  },
  {
    id: "species-downy-woodpecker",
    slug: "downy-woodpecker",
    commonName: "Downy Woodpecker",
    category: "birds",
    photoIds: ["photo-downy-woodpecker"],
  },
  {
    id: "species-white-lined-sphinx-moth",
    slug: "white-lined-sphinx-moth",
    commonName: "White-lined Sphinx Moth",
    category: "insects",
    photoIds: ["photo-sphinx-moth-hovering"],
  },
  {
    id: "species-common-green-darner",
    slug: "common-green-darner",
    commonName: "Common Green Darner",
    scientificName: "Anax junius",
    category: "insects",
    photoIds: ["photo-dragonfly-head-on-flight"],
  },
  {
    id: "species-crow",
    slug: "crow",
    commonName: "Crow",
    category: "birds",
    photoIds: ["photo-crow-portrait"],
  },
  {
    id: "species-blue-wasp",
    slug: "blue-wasp",
    commonName: "Blue Wasp",
    category: "insects",
    photoIds: ["photo-blue-wasp-white-flowers"],
  },
  {
    id: "species-coyote",
    slug: "coyote",
    commonName: "Coyote",
    scientificName: "Canis latrans",
    category: "mammals",
    photoIds: ["photo-coyote-standing", "photo-coyote-portrait"],
  },
  {
    id: "species-north-american-beaver",
    slug: "north-american-beaver",
    commonName: "North American Beaver",
    scientificName: "Castor canadensis",
    category: "mammals",
    photoIds: ["photo-beaver-lodge"],
  },
  {
    id: "species-deer",
    slug: "deer",
    commonName: "Deer",
    category: "mammals",
    photoIds: ["photo-deer-fawn"],
  },
];
