/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EducationRouteImport } from './routes/education'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrintsIndexRouteImport } from './routes/prints.index'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'
import { Route as PrintsSlugRouteImport } from './routes/prints.$slug'
import { Route as GallerySlugRouteImport } from './routes/gallery.$slug'

const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintsIndexRoute = PrintsIndexRouteImport.update({
  id: '/prints/',
  path: '/prints/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StoriesRoute,
} as any)
const PrintsSlugRoute = PrintsSlugRouteImport.update({
  id: '/prints/$slug',
  path: '/prints/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GallerySlugRoute = GallerySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GalleryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRouteWithChildren
  '/gallery/$slug': typeof GallerySlugRoute
  '/prints/$slug': typeof PrintsSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/prints/': typeof PrintsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRouteWithChildren
  '/gallery/$slug': typeof GallerySlugRoute
  '/prints/$slug': typeof PrintsSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/prints': typeof PrintsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRouteWithChildren
  '/gallery/$slug': typeof GallerySlugRoute
  '/prints/$slug': typeof PrintsSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/prints/': typeof PrintsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/catalog'
    | '/contact'
    | '/education'
    | '/gallery'
    | '/sitemap.xml'
    | '/stories'
    | '/gallery/$slug'
    | '/prints/$slug'
    | '/stories/$slug'
    | '/prints/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/catalog'
    | '/contact'
    | '/education'
    | '/gallery'
    | '/sitemap.xml'
    | '/stories'
    | '/gallery/$slug'
    | '/prints/$slug'
    | '/stories/$slug'
    | '/prints'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/catalog'
    | '/contact'
    | '/education'
    | '/gallery'
    | '/sitemap.xml'
    | '/stories'
    | '/gallery/$slug'
    | '/prints/$slug'
    | '/stories/$slug'
    | '/prints/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CatalogRoute: typeof CatalogRoute
  ContactRoute: typeof ContactRoute
  EducationRoute: typeof EducationRoute
  GalleryRoute: typeof GalleryRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoriesRoute: typeof StoriesRouteWithChildren
  PrintsSlugRoute: typeof PrintsSlugRoute
  PrintsIndexRoute: typeof PrintsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prints/': {
      id: '/prints/'
      path: '/prints'
      fullPath: '/prints/'
      preLoaderRoute: typeof PrintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/prints/$slug': {
      id: '/prints/$slug'
      path: '/prints/$slug'
      fullPath: '/prints/$slug'
      preLoaderRoute: typeof PrintsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$slug': {
      id: '/gallery/$slug'
      path: '/$slug'
      fullPath: '/gallery/$slug'
      preLoaderRoute: typeof GallerySlugRouteImport
      parentRoute: typeof GalleryRoute
    }
  }
}

interface GalleryRouteChildren {
  GallerySlugRoute: typeof GallerySlugRoute
}

const GalleryRouteChildren: GalleryRouteChildren = {
  GallerySlugRoute: GallerySlugRoute,
}

const GalleryRouteWithChildren =
  GalleryRoute._addFileChildren(GalleryRouteChildren)

interface StoriesRouteChildren {
  StoriesSlugRoute: typeof StoriesSlugRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesSlugRoute: StoriesSlugRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CatalogRoute: CatalogRoute,
  ContactRoute: ContactRoute,
  EducationRoute: EducationRoute,
  GalleryRoute: GalleryRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoriesRoute: StoriesRouteWithChildren,
  PrintsSlugRoute: PrintsSlugRoute,
  PrintsIndexRoute: PrintsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
